import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from app.config import settings
from typing import Dict
import html
from app.config import settings

def send_inquiry_email(user_email: str, user_question: str, chat_history_str: str) -> Dict:
    """
    Automatically determines the recipient based on keywords in the user's question.

    Args:
        user_email (str): User's email address for follow-up.
        user_question (str): User's last question that couldn't be answered.
        chat_history_str (str): Formatted chat history text.

    Returns:
        Dict: Status and message.
    """
    recipient_email = settings.DEFAULT_EMAIL_RECIPIENT
    question_lower = user_question.lower()

    if "tuition" in question_lower or "fee" in question_lower:
        # TsaiChen Lo (responsible for tuition fees related topics)
        recipient_email = settings.TUITION_EMAIL_RECIPIENT
    elif "application" in question_lower or "submit" in question_lower:
        # Duong Bui (responsible for application submission related topics)
        recipient_email = settings.APPLICATION_EMAIL_RECIPIENT
    elif "program" in question_lower or "select" in question_lower:
        # Rui Tang (responsible for advising which program to select)
        recipient_email = settings.PROGRAM_EMAIL_RECIPIENT

    try:
        msg = MIMEMultipart()
        msg['From'] = f"go42TUM Assistant <{settings.EMAIL_ADDRESS}>"
        msg['To'] = recipient_email
        msg['Subject'] = f"[go42TUM Inquiry] User question about: {user_question[:30]}..."

        escaped_question = html.escape(user_question)
        escaped_history = html.escape(chat_history_str)

        theme_color = "#3070b3"

        html_body = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>TUM Assistant Inquiry</title>
        </head>
        <body style="font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f4f4f4;">
            <div style="max-width: 600px; margin: auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 10px rgba(0,0,0,0.1);">
                <div style="background-color: {theme_color}; color: #ffffff; padding: 20px; text-align: center;">
                    <h1 style="margin: 0; font-size: 24px;">go42TUM Inquiry</h1>
                </div>
                <div style="padding: 20px;">
                    <p style="color: #333333; line-height: 1.6;">Dear TUM Staff,</p>
                    <p style="color: #333333; line-height: 1.6;">The AI assistant was unable to answer a user's question. Please review the details below and respond to the user directly.</p>
                    
                    <div style="background-color: #f9f9f9; border-left: 4px solid {theme_color}; padding: 15px; margin: 20px 0;">
                        <h3 style="margin-top: 0; color: {theme_color};">USER'S EMAIL FOR FOLLOW-UP</h3>
                        <p style="margin-bottom: 0; font-size: 16px;"><a href="mailto:{user_email}" style="color: #0056b3;">{user_email}</a></p>
                    </div>

                    <div style="margin: 20px 0;">
                        <h3 style="color: {theme_color};">FAILED QUESTION</h3>
                        <p style="background-color: #f9f9f9; padding: 15px; border-radius: 5px; color: #555555; font-style: italic;">
                            {escaped_question}
                        </p>
                    </div>

                    <div style="margin: 20px 0;">
                        <h3 style="color: {theme_color};">RECENT CONVERSATION HISTORY</h3>
                        <pre style="background-color: #f0f0f0; padding: 15px; border-radius: 5px; white-space: pre-wrap; word-wrap: break-word; font-size: 14px; color: #333333;">{escaped_history}</pre>
                    </div>
                </div>
                <div style="background-color: #eeeeee; color: #888888; text-align: center; padding: 10px; font-size: 12px;">
                    <p>This email was automatically generated by the TUM AI Assistant.</p>
                </div>
            </div>
        </body>
        </html>
        """

        msg.attach(MIMEText(html_body, 'html'))

        with smtplib.SMTP(settings.SMTP_SERVER, settings.SMTP_PORT) as server:
            server.starttls()
            server.login(settings.EMAIL_ADDRESS, settings.EMAIL_PASSWORD)
            server.send_message(msg)

        print(f"✅ Inquiry email sent successfully to {recipient_email}")
        return {
            "status": "success",
            "message": "The email was sent successfully."
        }
    except Exception as e:
        print(f"❌ Error sending email: {e}")
        return {
            "status": "error",
            "message": f"Failed to send email. Encountered this error: {e}"
        }